---

- name: Install smartmontools
  apt: 
    name: smartmontools
    state: present

- name: Update smartctl so we can run it as a user
  command: chmod +s /usr/sbin/smartctl

- name: Use datadogs built in pip command to install pysmart
  command: /opt/datadog-agent/embedded/bin/pip install pysmart

- name: Make smartdog directory in conf
  file:
    path: /etc/datadog-agent/conf.d/smartmonctl.d
    owner: dd-agent
    group: dd-agent
    state: directory

- name: Add config to Datadog
  template:
    src: "smartmonctl.yaml.j2"
    dest: "/etc/datadog-agent/conf.d/smartmonctl.d/smartmonctl.yaml"
    force: no
    owner: dd-agent
    group: dd-agent
  notify:
    - restart datadog-agent

- name: Add to checks
  template:
    src: "smartmonctl.py.j2"
    dest: "/etc/datadog-agent/checks.d/smartmonctl.py"
    owner: dd-agent
    group: dd-agent
    force: no
  notify: 
    - restart datadog-agent
